#!/bin/bash

TMP_SRT="0759FF40-2FEC-446A-AC74-9AD1A68F2882.srt"

echo "00:00 Movie file $1."
ffmpeg -i "$1" -vn -an -codec:s:0 srt "$TMP_SRT" >ffmpeg.log 2>&1
echo "00:03 Captions have been extracted."
./srt_forHuman.rb "$TMP_SRT" > $1.txt
echo "00:09 Get them from $1.txt."

rm -f "$TMP_SRT"
