#!/bin/bash

TMP_SRT="0759FF40-2FEC-446A-AC74-9AD1A68F2882.tmp"

ffmpeg -i "$1" -vn -an -codec:s:0 srt "$TMP_SRT" >ffmpeg.log 2>&1
./str_humanizer.rb "$TMP_SRT" > $1.txt
rm -f "$TMP_SRT"
echo "$1.txt contains human readble movie captions"
